# Generated by Django 5.0 on 2024-03-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myforms', '0002_remove_formdata_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formdata',
            table='FormData',
        ),
    ]
