# Generated by Django 5.0 on 2024-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myforms', '0003_alter_formdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formdata',
            table='Persons',
        ),
    ]
