# Generated by Django 5.0 on 2024-03-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myforms', '0004_alter_formdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formdata',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
